version: '3.8'
services:
  mysql57:
    image: mysql:8.0.29
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: market_management
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production #alteração aqui
    depends_on:
      mysql57:
        condition: service_healthy
    env_file:
      - .env

volumes:
  mysql_data: